### PR TITLE
Fix (and rewrite) `dx init`/`dx new`

### PR DESCRIPTION
**Pull request by Andrew15-5**
Fixes issue in https://github.com/DioxusLabs/dioxus/issues/2788#issuecomment-2270538452. I have found few semantic breakages and bugs, but upon trying to fix stuff and dig deeper to get the whole image of what the current state of `init`/`new` subcommands is trying to do, I stumbled upon even more bugs and performance issues (calling `MetadataCommand` from incorrect CWD causes a 2 s slowdown!). Here is my [monologue](https://discord.com/channels/899851952891002890/936277970644000778/1272266828894437376) with a little bit more context.

Here I am cooking a new version of those subcommands. The workspace change will be mostly untouched as I'm not familiar with it, and it doesn't overlap with the problem at hand.

The first commit contains a ton of commented code, which most likely breaks the `new` command (at least in some way). But I fully rewrote (refactored + added a few things) the `init` command. Had to get an absolute path without resolving symbolic links, so I used a `path-absolutize` crate (for free). Second commit adds one dev dependency for running and testing commands (including `dx`), it's pretty small. I rarely wrote tests before, but these once look very nice. I think I balanced abstraction and clarity pretty well.

One thought I now have (since my testing strategy has changed from the beginning) is to put `init` subcommmand tests to its own file instead of the main one.

Notes (to not forget):
- Currently no way to use non-default branch (tag/revision) when using a cargo-generate template. Need to add/copy `branch`, `tag`, `revision` options from cargo-generate. Should this be a separate PR or it can be included here? It by itself probably will be very small.

### CODE REVIEW

**Comment by Andrew15-5** [comment]
I also added the `branch` option to be able to use (unmerged) branches from a remote template (git) repository (https://github.com/DioxusLabs/dioxus/issues/2788#issuecomment-2270538452). As a complete set, also added `revision` and `tag` options. This will open a possibility for a wider range of reproducible projects/bugs.

**Comment by Andrew15-5** [comment]
Current implementation of `dx init` and `dx new` follows the behavior of `cargo init` and `cargo new` respectively. Specifically, how `path` and `name` work. This is technically a breaking change, but for most use cases almost nothing has changed. IMO, the most noticeable change is that `path` is required for `dx new`. I laid out the problem [here](https://discord.com/channels/899851952891002890/936277970644000778/1274110035928027207).

**Comment by Andrew15-5** [comment]
Another notes:
- `vcs` not only practically was set to None in both branches of the condition, but it also was loosely dependent on `metadata` which feels like not a good thing to do. Moreover, cargo-generate won't create a VCS if already inside VCS. And lastly, if anything, we can have a `--vcs` option to use it directly as intended.
- the mutual exclusivity of some options is enforced by clap, so I'm not sure if tests for this should be written, but my gut feeling says that they should be, just in case.
- [here](https://github.com/DioxusLabs/dioxus/pull/2822/files#diff-03993b5e442e077ccb1304ee14eb355c979828aace31c370b2dddc7cbe6ec209R113-R127) I'm pretty confident that I set a correct current directory for metadata command, but not on 100%.
- I could've compressed the tests more by substituting repetitive code with a macro, so that it will show panic in the correct place (2 places), but it seems a bit less readable, including more verbose logs.
- maybe use a local (in-repo) micro-template for the tests? This will remove the necessity for Internet connection and that you must pass the `--subtemplate` option until https://github.com/cargo-generate/cargo-generate/issues/1181 is fixed. Reducing things that can go wrong is always better.

**Comment by Andrew15-5** [comment]
I found that `Error::CargoMetadata` variant is gone, so I recreated it in the place where it used before it was removed.

I was surprised that the tests failed after I initially thought that I'm done. But apparently I was not the first one: https://github.com/assert-rs/assert_cmd/issues/131. So because of this [limitation](https://docs.rs/assert_cmd/2.0.16/assert_cmd/cargo/#limitations) I used `escargot` instead of `assert_cmd`. I did use the new (fancy) `LazyLock` for static one-time cargo build, which is expensive to call.

The tests still pass without any changes, so that's cool. :)

Do we need some sort of "workspace" `dx new`/`dx init` tests?

Also, I updated the `Cargo.lock` file, which is now has some crates with newer versions. Is it fine, or should I revert them?

**Comment by Andrew15-5** [comment]
Oh no... It's still not in the stable version (for some platforms?).
https://github.com/DioxusLabs/dioxus/actions/runs/11802634307/job/32878728014?pr=2822

**Comment by Andrew15-5** [comment]
I also think that renaming `Create` to `New` would be a bit more intuitive, since it's responsible for the `dx new` subcommand.

**Comment by jkelleyrtp** [comment]
Thanks! Will take a look tomorrow - might be able to get it into the release.

**Review by jkelleyrtp — APPROVED** [review]
Actually, all looks good, thank you!

**Comment by Andrew15-5** [comment]
Oh, wow, OK. Great, but what about questions from https://github.com/DioxusLabs/dioxus/pull/2822#issuecomment-2471110440 and https://github.com/DioxusLabs/dioxus/pull/2822#issuecomment-2471282670?

**Comment by jkelleyrtp** [comment]
> Do we need some sort of "workspace" dx new/dx init tests?

Eventually, sure, plus a whole slew of other tests for the CLI. But for now it's not a big deal - the code here isn't too crazy to make it worth not shipping it in 0.6.

> I also think that renaming Create to New 

We could but it doesn't seem terribly important to do that either.

**Comment by Andrew15-5** [comment]
Alright, and the last question from the https://github.com/DioxusLabs/dioxus/pull/2822#issuecomment-2471110440. I guess slightly more up-to-date random crates isn't an issue either? I thought that this could add some potential problems, but maybe it's fine since all the current tests are passing.

**Pull request merged**
