### PR TITLE
Fix events with a text node target

### LINKED ISSUE #1317: Dioxus desktop: Event handler javascript error for event "onselectstart" on element with "contenteditable" attribute
**Problem**

Elements with the ```contenteditable``` attribute set, cause a javascript error in the event handler code when receiving the ```selectstart``` event, on dioxus-desktop for linux.

The generated error on the console is:
```TypeError: target.getAttribute is not a function. (In 'target.getAttribute(`dioxus-prevent-default`)', 'target.getAttribute' is undefined)```

The line of code causing this problem is:
```let preventDefaultRequests = target.getAttribute(`dioxus-prevent-default`);```

**Steps To Reproduce**

- Create a dioxus-desktop project with this code:
```rust
use dioxus::prelude::*;

fn main() {
    dioxus_desktop::launch(app);
}

fn app(cx: Scope) -> Element {
    render!{
        div {
            onselectstart: move |_| println!("event"),
            contenteditable: "true",
            "Test"
        }
    }
}
```
- Start selecting the text inside the div;
- The ```println!``` will not be triggered and in the javascript console there will be the error I mentioned before.

**Expected behavior**

The javascript event handler shouldn't throw this error and the onselectstart rust lambda should be triggered.

**Environment:**
 - Dioxus version: `0.4.0`
 - Rust version: `1.73.0-nightly`
 - OS info: `linux X11`
 - App platform: `desktop`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### PR DESCRIPTION
**Pull request by ealmloff**
The interpreter code assumed that the target was an element node, but some events can be triggered on text nodes. This PR checks that the target is a element node before reading attributes

Fixes #1317

### CODE REVIEW

**Comment by samu698** [comment]
Hello, It's been a month since this PR and my issue are open, how long will it take before it will be merged, is there something you are waiting on? Or there are problems with the PR?
Thank you

**Comment by ealmloff** [comment]
> Hello, It's been a month since this PR and my issue are open, how long will it take before it will be merged, is there something you are waiting on? Or there are problems with the PR? Thank you

**Comment by ealmloff** [comment]
I'm just waiting on a review, as far as I know this works. If you would like to use this fix before the PR is merged you can change your dependency to:
```toml
dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "fix-text-node-target-events" }
dioxus-web = { git = "https://github.com/ealmloff/dioxus", branch = "fix-text-node-target-events" }
```

**Review by jkelleyrtp — APPROVED** [review]

**Comment by jkelleyrtp** [comment]
> Hello, It's been a month since this PR and my issue are open, how long will it take before it will be merged, is there something you are waiting on? Or there are problems with the PR?
> Thank you

Just busy on the administrative side of things! Big push for PRs and patch releases today.

**Pull request merged**
