### PR TITLE
feat: add "optional" flag for props

### PR DESCRIPTION
**Pull request by jkelleyrtp**
Adds the flag "optional" to props that combines default and strip_option

### CODE REVIEW

**Comment by mrxiaozhuox** [comment]
so the `optional`  modifiers have not been merged?
now just can use `default`

**Comment by jkelleyrtp** [comment]
> so the `optional` modifiers have not been merged?
> now just can use `default`

Yes - "optional" is just "default" + "strip_option" which you can do today. This updates the code so the docs match up

**Comment by mrxiaozhuox** [comment]
I think we need declare the version you can use in document, because in document have many feature is not complete. we need tell them is unfinished.

**Review by mrxiaozhuox — COMMENTED** [review]
LGTM

**Pull request merged**
