### PR TITLE
Unify Collecting and Optimizing Assets

### LINKED ISSUE #1283: Unified Asset Solution
## Specific Demand

Currently, different platforms manage assets in different ways. Dioxus desktop requires you to create a custom head, and dioxus web uses the dioxus.toml file. There is also a separate config section for bundling assets.

### Minimal

Move all asset configuration into the Dioxus.toml file. The Desktop/Mobile/Blitz renderers can include the file with a macro at compile time. All platforms read the file at runtime and include the assets in a platform specific way. We can also use this asset section for bundling purposes.

### Complete

We could create an asset macro that allows you to include an asset in your rust code. This would make including a library that uses assets automatically add those assets to your final bundle.

```rust
// Component library that uses tailwind
asset!("tailwind.css");
```

```rust
// This would pull in the tailwind.css file
use tailwind_components::Comp;
```

To collect the assets we would need to use either [LinkMe](https://github.com/dtolnay/linkme) or custom WASM sections like the [wasm-bindgen] macro. Both of these solutions would require some runtime like the dioxus-cli that knows how to collect that information from the final binary to determine what assets should be bundled

### PR DESCRIPTION
**Pull request by ealmloff**
This PR creates a unified asset solution for all Dioxus renderers/bundlers.

# Collect Assets

Asset collection and optimization happens in the new [collect asset](https://github.com/DioxusLabs/collect-assets) library. This PR just integrates that list of assets into the CLI bundler and assets directory. In order to make cargo run work, we also need to collect assets in the desktop, and fullstack launch functions.

This will unblock a cross platform UI library:

```
- [ ] A cross-platform component library like tamagui
```

This PR should also be a stepping stone towards much of the work on deploy tooling which needs us to collect different metadata at compile time:

```
- [ ]  Tracing for server functions
- [ ]  Devtools for components
- [ ]  Binary analysis for server functions and assets
```

Closes #1283 

TODO:
- [x] Copy assets into the build directory in the CLI
- [x] Integrate assets into the bundler
- [x] Copy assets in the Desktop launch function

```toml
[package]
name = "dioxus-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assets-git-link-test = { git = "https://github.com/Demonthos/assets-git-link-test" }
dioxus = { git = "https://github.com/Demonthos/dioxus", branch = "intigrate-collect-assets" }
dioxus-fullstack = { git = "https://github.com/Demonthos/dioxus", branch = "intigrate-collect-assets" }
serde = "1.0.159"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus-desktop = { git = "https://github.com/Demonthos/dioxus", branch = "intigrate-collect-assets" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus-web = { git = "https://github.com/Demonthos/dioxus", branch = "intigrate-collect-assets" }

[features]
default = []
ssr = ["dioxus-fullstack/axum"]
web = ["dioxus-fullstack/web"]
```

```rust
use dioxus::prelude::*;
use assets_git_link_test::*;

#[cfg(any(feature = "web", feature = "ssr"))]
use dioxus_fullstack::prelude::*;

fn main() {
    #[cfg(any(feature = "web", feature = "ssr"))]
    LaunchBuilder::new(app).launch();
    #[cfg(not(target_arch = "wasm32"))]
    dioxus_desktop::launch(app);
    #[cfg(target_arch = "wasm32")]
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    let assets = [TEST_ASSET, IMAGE_ASSET, PNG_ASSET, RESIZED_PNG_ASSET, JPEG_ASSET, RESIZED_JPEG_ASSET, WEBP_ASSET, RESIZED_WEBP_ASSET];

    render! {
        for img in assets {
            div {
                img {
                    src: img,
                    width: "100px",
                    height: "100px",
                }
                img
            }
        }
        p {
            font_family: "Comfortaa",
            "thin font"
        }
    }
}
```

Screenshot 2023-08-17 at 10 01 42 AM

### CODE REVIEW

**Comment by Demonthos** [comment]
Fullstack support for bundling assets is blocked on https://github.com/DioxusLabs/dioxus/issues/1334. We need to set some environment variables differently for fullstack

**Comment by tigerros** [comment]
Will this minify and bundle the output HTML and JS?

**Comment by ealmloff** [comment]
> Will this minify and bundle the output HTML and JS?

Not yet, but we should add support for minifying those assets to [magnanis](https://github.com/DioxusLabs/collect-assets).

Currently it supports:
- [x] Support optimizing assets
- - [x] PNG
- - [x] JPG
- - [x] Convert images
- - [x] Resize images
- - [x] CSS
- - [x] Self-host remote assets (fonts)
- [x] Google Fonts Integration
- [x] Deduplicate assets
- [x] Collect assets from dependencies
- [x] Tailwind

**Comment by tigerros** [comment]
> Not yet, but we should add support for minifying those assets to [magnanis](https://github.com/DioxusLabs/collect-assets).

I would love to help, but I don't know how to test it. I ran the `test-package` example but the only files that were outputted to `assets/` is `tailwind.css`. That might because of an error with `manganis::file!("./test-package-dependency/src/asset.txt")`, which returns `/assetsasset.txt` instead of `/assets/asset.txt`.

**Comment by ealmloff** [comment]
> > Not yet, but we should add support for minifying those assets to [magnanis](https://github.com/DioxusLabs/collect-assets).
> 
> I would love to help, but I don't know how to test it. I ran the `test-package` example but the only files that were outputted to `assets/` is `tailwind.css`. That might because of an error with `manganis::file!("./test-package-dependency/src/asset.txt")`, which returns `/assetsasset.txt` instead of `/assets/asset.txt`.

This should be fixed. I was trying to optimize a function but accidentally changed the behavior to make the paths that the macro wrote to and the CLI read from different

**Pull request merged**
