### PR TITLE
Create use_eval for liveview

### PR DESCRIPTION
**Pull request by Demonthos**
Creates a use_eval hook (functioning the same as the desktop use_eval hook) for the liveview renderer to allow liveview programs to interact with browser APIs

### CODE REVIEW

**Comment by jonay2000** [comment]
This feature is hard to use, since the error use_eval returns (`QueryError`) is public in a private module (`query`) and can therefore not be imported. Is `QueryErrror` the right error for this?

**Comment by jonay2000** [comment]
I figured out why the future never resolves, the resoponse to the query contains no "data" field, which means serde cannot deserialize the response. Unfortunately, the error is silent.

**Comment by jonay2000** [comment]
I think this could be filled by adding 
```js
|| null
```

to this line https://github.com/DioxusLabs/dioxus/blob/b264211cc2685232426317d3055046838047d3db/packages/liveview/src/query.rs#L49

**Comment by jonay2000** [comment]
As well as that, I recommend logging errors when deserialization fails here
https://github.com/DioxusLabs/dioxus/blob/b264211cc2685232426317d3055046838047d3db/packages/liveview/src/pool.rs#L163

**Review by jonay2000 — CHANGES_REQUESTED** [review]
see previous comments

**Comment by Demonthos** [comment]
Thanks for letting me know about those issues. They should be fixed now, if it fails to deserialize the return value, it will now default to Null.

You don't need to await a use_eval hook that returns nothing unless you need to know when it finishes. The code will run in the browser even if you do not await the future.

**Comment by jonay2000** [comment]
awesome!

I know I don't need to await it, but for my logic it makes a lot of sense to do so anyway.

**Comment by jonay2000** [comment]
and I see QueryError is public now too :)

**Review by jonay2000 — APPROVED** [review]

**Comment by jonay2000** [comment]
One more thing, maybe put in the documentation that to return a value you need to explicitly use `return`.

**Pull request closed without merging**
