### PR TITLE
adds pipeline to bump semver and release to crates.io automatically

### PR DESCRIPTION
**Pull request by alexanderjophus**
I can't figure out how to mark this as a draft myself, but I want to check a few things before this is actually ready.

This change introduces a new pipeline for the maintainers to release dioxus in a simple manner.

Things to note:

- The following diff is necessary, this defaults to the code in the workspace enabling maintainers/contributors to easily and quickly write code across different crates. The version should be maintained by a bot and automatically bumped as/when a new version is released, it is required for `cargo workspaces` to work (as it depends on crates.io's requirements of there being a version number)
```diff
+ dioxus-rsx = { workspace = true, version = "0.4.2" }
- dioxus-rsx = { workspace = true }
```

- I'm still trying to figure out how to solve for unreleased packages such as signals and generational-box. I _believe_ `cargo workspaces` allows you to specify which packages to release but this is not implemented yet. As such, the PR as it stands would bump everything to `0.4.3` on the next patch regardless of if it's `0.4.2` now or `0.0.0`.

Fixes part of https://github.com/DioxusLabs/dioxus/issues/1539

Example commit in the much simpler [slides project](https://github.com/alexanderjophus/dioxus-slides/commit/3c52b02bc2e3fd0a6b0e732cfee80881565d8632) I'm working on. Note how it maintains the version in all the packages.

### CODE REVIEW

**Comment by alexanderjophus** [comment]
After a discussion with Marc on discord, we're going to try pinning to `0.4` to see what happens, otherwise it may publish unnecessary versions a lot.

**Comment by alexanderjophus** [comment]
Looks like pinning to 0.4 will also work and is possibly preferable.

Proof: https://github.com/alexanderjophus/dioxus-slides/actions/runs/6840221582/job/18599245617

**Comment by alexanderjophus** [comment]
Noticed there's a possible hiccup with this when running some examples.

My terminal gets littered with these - exploring options now:
```
warning: /Users/ajt/projects/tmp/dioxus/packages/dioxus-tui/Cargo.toml: unused manifest key: dependencies.dioxus-core.version
```

**Comment by ealmloff** [comment]
> Noticed there's a possible hiccup with this when running some examples.
> 
> My terminal gets littered with these - exploring options now:
> 
> ```
> warning: /Users/ajt/projects/tmp/dioxus/packages/dioxus-tui/Cargo.toml: unused manifest key: dependencies.dioxus-core.version
> ```

dioxus-tui might not use dioxus-core anymore (instead it just uses dioxus). You could try entirely removing the dependency

**Comment by alexanderjophus** [comment]
The only fix I've found is the following in the package cargo.toml files. 
```diff
+ dioxus = { path = "../dioxus", version = "0.4" }
- dioxus = { workspace = true, version = "0.4" }
```
I tried various permutations in the root Cargo.toml file, most googling suggests .cargo/config.toml, which showed no luck either.

**Comment by ealmloff** [comment]
> The only fix I've found is the following in the package cargo.toml files.
> 
> ```diff
> + dioxus = { path = "../dioxus", version = "0.4" }
> - dioxus = { workspace = true, version = "0.4" }
> ```
> 
> I tried various permutations in the root Cargo.toml file, most googling suggests .cargo/config.toml, which showed no luck either.
> 
> Question for yourself is; is that ok?

That wouldn't be great. using workspace dependancies makes it much easier to move around, rename and add new crates. What exactly caused the error? Did adding the versions cause the error? Is it an issue in cargo workspace? It seems like this might be related to https://github.com/pksunkara/cargo-workspaces/pull/56. In the discussion, there is a fork linked that fixed this issue. Maybe we could try that fork

**Comment by alexanderjophus** [comment]
Not sure I have the bandwidth to finish this. I do agree that we should stick with the `workspace = true` setting.

As far as I know that ticket you linked is not related (could be wrong though), but I do think the issue is in cargo workspace, I've just not dug through to find out more.

**Comment by jkelleyrtp** [comment]
Hey! Thanks for getting this off the ground. This is exactly what we need. I'll work on bringing it up to speed.

**Pull request closed without merging**
