### PR TITLE
add aria-current to link

### PR DESCRIPTION
**Pull request by uzytkownik**

### CODE REVIEW

**Review by jkelleyrtp — CHANGES_REQUESTED** [review]
Tests are failing since we snapshot test the HTML and it's not expecting the aria label. Can we fix that test?

**Comment by uzytkownik** [comment]
@jkelleyrtp how do I run locally? I did `cargo test` and `cargo clippy` before submission.

**Comment by ealmloff** [comment]
There is a list of commands CI runs here: https://dioxuslabs.com/learn/0.5/contributing#before-you-contribute. The main command for testing is:
```
cargo test --all --tests
```

**Comment by uzytkownik** [comment]
@ealmloff It might be better to add CONTRIBUTING.md. Plus the code seems to be outdated:

```
% cargo fmt -- src/**/**.rs
Error: file `src/**/**.rs` does not exist
```

**Review by ealmloff — APPROVED** [review]

**Pull request merged**
