### PR TITLE
Partially Fix Hotreload

### LINKED ISSUE #2180: Tailwind classes are not hot reloaded
**Problem**

The blog post says that tailwind classes can now be hot reloaded, but they currently require a full recompile

**Steps To Reproduce**

- Clone the dioxus repo (rev 2461790baf302766f35861c3c85269ba90add247)
- Run:
```sh
cd examples/tailwind
dx serve
```
- Run in another terminal:
```sh
cd examples/tailwind
npx tailwindcss -i ./input.css -o ./public/tailwind.css --watch
```
- Change a tailwind class
- Observe a normal rust recompile

**Expected behavior**

In the blog post we mention that tailwind hot reloading is supported:
Screenshot 2024-03-29 at 8 32 45 AM

**Environment:**
 - Dioxus version: `master`
 - Rust version: `nightly`
 - OS info: MacOS
 - App platform: `web`

**Questionnaire**

- [ ] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### PR DESCRIPTION
**Pull request by DogeDark**
- Normalizes all template names to follow `foo/bar/baz.rs`
- Fixes a caching issue on Web with re-sending the templates that occurred before a full reload.

This gets hot reloading working on Web for the Tailwind example. Desktop requires more work as it's affected by #1586 and #2486. 

I noticed that there were two separate socket systems between Web & Desktop. I think these should be merged into the Web's socket system with the communication models being standardized between them. This would also allow hot reload to a mobile device from the host machine in the future.

Half-Fixes #2180 but should fix any tailwind/hotreload in cases where `\n` or `\t` aren't used in RSX.

**Testing:**
To test if the template path name standardization logic works correctly between platforms.
- [x] Windows
- [x] Linux (I'll test this)
- [ ] Mac

### CODE REVIEW

**Comment by DogeDark** [comment]
Looks like these issues might already be fixed in #2258.

**Comment by jkelleyrtp** [comment]
I'm not normalizing path names so that's still a useful change. If this is something we can backport then I'd still like to accept this PR so we can get it out to Dioxus 0.5 users!

**Comment by jkelleyrtp** [comment]
Oh, I think I *did* #1586 in my PR. We were to_string the wrong thing and it wasn't escaping stuff correctly. Need to check,

**Comment by DogeDark** [comment]
Maybe we could backport a fix for that too?

**Pull request merged**
