### PR TITLE
A partial implementation of the router and associated bits

### PR DESCRIPTION
**Pull request by autarch**

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
When you get a chance, you can rebase to get the fixes from #108

**Comment by autarch** [comment]
> Thank you!! When you get a chance, you can rebase to get the fixes from #108

Done.

**Comment by jkelleyrtp** [comment]
Would you like me to review this? Looks pretty functional :)

**Comment by autarch** [comment]
> Would you like me to review this? Looks pretty functional :)

Yes, please do. I think there's enough here to at least figure out if this is the right design. I can make further changes or I'm happy to have you make commits directly. I can also rebase this as needed.

**Comment by jkelleyrtp** [comment]
Since the Router still needs some configuration for desktop support, I'm going to merge this as is and then follow it up with a PR that you can review.

Thank you for adding this! It's amazing to have full (almost) router support now!

**Pull request merged**
