### PR TITLE
Fix prop docs line breaks

### PR DESCRIPTION
**Pull request by tigerros**
I'm sorry for creating a third PR for this, but I just noticed that there's one too many line breaks in the generated docs for props (see https://github.com/DioxusLabs/dioxus/pull/1563 and https://github.com/DioxusLabs/dioxus/pull/1565). I changed it to use the Rustdoc approach, which puts text separated by two lines into separate `<p>` elements. Previously, it just replaced `\n` with `<br/>`

Right now, this documentation:
```
/// Doc.
/// Next line.
```

Would generate:

```
Doc.
Next line.
```

But it's actually supposed to be:

```
Doc. Next line.
```

And when you used two new lines, the gap between them would be too big. Example image with the bug:
image
Fixed:
image
Regular Rustdoc:
image

### CODE REVIEW

**Comment by tigerros** [comment]
I'm confused. `cargo check --all --examples --tests` compiles on my machine. I didn't change any versions either which seems to be the problem...

**Comment by ealmloff** [comment]
> I'm confused why the checks are failing. cargo check --all --examples --tests compiles on my machine. I didn't change any versions either which seems to be the problem...

Some dependency of dioxus may have updated within the last hour since the previous CI run

**Comment by tigerros** [comment]
I ran `cargo update` and `cargo check --all --examples --tests` and still no error. Could you re-run the checks? If not, I can make an empty commit.

**Comment by jkelleyrtp** [comment]
Looks great - thanks @tigerros !

**Review by jkelleyrtp — APPROVED** [review]

**Pull request merged**
