### PR TITLE
Tui input widget

### PR DESCRIPTION
**Pull request by Demonthos**
Add widgets to the tui renderer, and a general purpose cursor struct for any renderers.
Todo:
- [x] Textbox
- - [x] Basic Keyboard Editing
- <del> Insert Mode</del>
- - [x] Mouse Support
- - [x] size
- - [x] maxlength
- - [x] Use terminal cursor
- [x] Checkbox
- [x] Password
- - [x] Hide characters
- [x] Button
- - [x] onclick
- [x] Number
- - [x] Limit to only numbers
- - [x] Up/Down with arrow keys
- - [x] Up/Down buttons
- [x] Range
- - [x] Left/Right with keyboard
- - [x] Mouse Support
- - [x] Min/Max
- - [x] Step

Depends on:
#400
#390

Demo:

https://user-images.githubusercontent.com/66571940/167262687-a8423500-00ae-4ac6-883a-899b59b646f8.mp4
 
Future work: pass through global attributes

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
This is so exciting!!!!!!!!!!

**Review by jkelleyrtp — APPROVED** [review]
I might come in and clean up a few things like formatting and such after this is merged, but this looks great otherwise.

**Comment by mattoni** [comment]
This is awesome, can't wait for this to be merged.

**Comment by jkelleyrtp** [comment]
Do you need any help resolving conflicts here?

**Comment by Demonthos** [comment]
> Do you need any help resolving conflicts here?

I've copied over most of the changes to a up to date branch. I need to update some things that changed with templates but hopefully I can finish up tomorrow

**Comment by Demonthos** [comment]
Conflicts fixed, but this branch has a bunch of files marked as changed that should not be. #646 has the same changes recreated from master

**Pull request closed without merging**
