### PR TITLE
Fix event multi node event bubbling

### LINKED ISSUE #867: Event propagation fails
**Problem**

Children with onpointerdown or onclick events block propagation of pointer events to their parent.

**Steps To Reproduce**

1) make a parent div with two child divs.
2) assign `onpointermove` and `onpointerdown` events to the parent that log when triggered.
3) assign an `onpointerdown` or `onclick` event to only one of the children that logs when triggered.
4) observe that mouse interaction with the event-free child triggers the parent's event logs as expected.
4) observe that when the mouse is moved across the child with an `onpointerdown` event, the parent's `onpointermove` event is not logged.
5) observe that when the mouse is clicked on the child with the `onpointerdown` event, the parent's `onpointerdown` event is not logged.

**Expected behavior**

moving the mouse across either child div should trigger the parent's `onpointermove` event log. Would be helpful in making draggable divs.

**Environment:**
 - Dioxus version: 3.2
 - Rust version: 1.67.1
 - OS info: WSL2 Ubuntu, running the app with Trunk.
 - App platform: web - 0.3.1

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start 
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

Main.rs
```
#![allow(non_snake_case)]
use dioxus::prelude::*;

fn main() {
    wasm_logger::init(wasm_logger::Config::new(log::Level::Info));
    dioxus_web::launch(app);
}

fn app(cx: Scope) -> Element {
    cx.render(rsx!{
        div {
            style: "width: 300px; height: 300px; background-color: blue;",
            onpointermove: move |_| log::info!("pointer moving on container"),
            onpointerdown: move |_| log::info!("pointer down on container"),
            div {
                style: "margin: 10px; width: 100px; height: 100px; background-color: yellow;",
                "no onpointerdown or click event",
            },
            div {
                style: "margin: 10px; width: 100px; height: 100px; background-color: red;",
                onpointerdown: move |_| log::info!("pointer down on CHILD"),
                "onpointerdown event"
            },
        },
        p {
            "Children with onpointerdown or onclick events specified do not allow pointer events to propagate to their parent"
        },
        p {
            "view console for details"
        }
    })
}
```
index.html
```
<!DOCTYPE html>
<html lang="en">
    <head> 
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <title>Pointer Event Bug</title>
    </head>
    <body>
      <div id = "main">
       
      </div>
    </body>
</html>
```
Cargo.toml
```
[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"

log = "0.4"
wasm-logger = "0.2.0"
```

### PR DESCRIPTION
**Pull request by ealmloff**
This PR splits the elements slot map into two different maps:
- A elements map for the element ids that are currently being used in the renderer
- A map of references into VNodes for bubbling

Closes #867 

todo:
- [x] recycle bubble ids

### CODE REVIEW

**Comment by marc2332** [comment]
Is this still work in progress? 😄 Just asking! I tried to run it but ran into this:

```
error[E0061]: this method takes 2 arguments but 4 arguments were supplied
   --> C:\Users\mespi\.cargo\git\checkouts\dioxus-5df58c476196bcfb\e337aff\packages\core\src\create.rs:185:22
    |
185 |                 self.create_dynamic_node(template, idx, node, idx)
    |                      ^^^^^^^^^^^^^^^^^^^ --------  ---        --- unexpected argument of type `usize`
    |                                          |         |
    |                                          |         unexpected argument of type `usize`
    |                                          expected `BoundaryRef<'_>`, found `&VNode<'_>`
    |
note: method defined here
   --> C:\Users\mespi\.cargo\git\checkouts\dioxus-5df58c476196bcfb\e337aff\packages\core\src\create.rs:447:19
447 |     pub(crate) fn create_dynamic_node(
    |                   ^^^^^^^^^^^^^^^^^^^
448 |         &mut self,
449 |         parent: BoundaryRef<'b>,
    |         -----------------------
450 |         node: &'b DynamicNode<'b>,
    |         -------------------------
help: remove the extra arguments
    |
185 -                 self.create_dynamic_node(template, idx, node, idx)
185 +                 self.create_dynamic_node(/* BoundaryRef<'_> */, node)
    |

error[E0061]: this method takes 2 arguments but 4 arguments were supplied
   --> C:\Users\mespi\.cargo\git\checkouts\dioxus-5df58c476196bcfb\e337aff\packages\core\src\create.rs:269:26
    |
269 |             let m = self.create_dynamic_node(template, idx, &template.dynamic_nodes[idx], idx);
    |                          ^^^^^^^^^^^^^^^^^^^ --------  ---                                --- unexpected argument of type `usize`
    |                                              |         |
    |                                              |         unexpected argument of type `usize`
    |                                              expected `BoundaryRef<'_>`, found `&VNode<'_>`
    |
note: method defined here
   --> C:\Users\mespi\.cargo\git\checkouts\dioxus-5df58c476196bcfb\e337aff\packages\core\src\create.rs:447:19
    |
447 |     pub(crate) fn create_dynamic_node(
    |                   ^^^^^^^^^^^^^^^^^^^
448 |         &mut self,
449 |         parent: BoundaryRef<'b>,
    |         -----------------------
450 |         node: &'b DynamicNode<'b>,
    |         -------------------------
help: remove the extra arguments
    |
269 -             let m = self.create_dynamic_node(template, idx, &template.dynamic_nodes[idx], idx);
269 +             let m = self.create_dynamic_node(/* BoundaryRef<'_> */, &template.dynamic_nodes[idx]);
    |

For more information about this error, try `rustc --explain E0061`.
error: could not compile `dioxus-core` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `dioxus-core` (lib) due to 2 previous errors
```

**Comment by ealmloff** [comment]
It looks like one of the merges got messed up

**Comment by marc2332** [comment]
> It looks like one of the merges got messed up

ahhh! Do you mind fixing it, and maybe even updating the branch with the changes from develop? ❤️ I'd like to give this PR a try 😄

**Comment by marc2332** [comment]
I wonder why the CI says ✅  in everything while there are compilation errors, weird!

**Comment by ealmloff** [comment]
Oh, the issue is even more odd than that. I somehow managed to create two completely different branches with the same name. This version works, the other branch with the same name does not work

**Comment by ealmloff** [comment]
There is one letter different. Is there any chance you used `fix-event-bubling`? instead of `fix-event-bubbling`?

**Comment by marc2332** [comment]
I actually used the commit hash `e337aff0a443297c7d4f14b1bb5e1ad23963f10e` from this PR, which uses the branch `fix-event-bubbling` from your fork

**Comment by marc2332** [comment]
oh man I am so dumb.

**Comment by marc2332** [comment]
I actually copied the hash from the first commit and not the latest... I swear I hate GitHub's UI sometimes...

**Comment by marc2332** [comment]
that explains why the CI was ✅ 😭

**Comment by JMS55** [comment]
Something seems broken related to event handling and bubbling events up from dynamic nodes. This test fails for me:
```rust
static FOO_CLICK: Mutex<usize> = Mutex::new(0);

fn foo(cx: Scope) -> Element {
    let x = "Ahh";
    render! {
        div {
            onclick: |_| {
                *FOO_CLICK.lock().unwrap() += 1;
            },
            format!("{x}")
        }
    }
}

#[test]
fn foo_test() {
    let mut dom = VirtualDom::new(foo);
    _ = dom.rebuild();

    // ElementId 2 = The dynamic text node
    dom.handle_event("click", Rc::new(MouseData::default()), ElementId(2), true);
    assert_eq!(*FOO_CLICK.lock().unwrap(), 1);
}
```

**Comment by ealmloff** [comment]
> Something seems broken related to event handling and bubbling events up from dynamic nodes. This test fails for me:
> 
> ```rust
> static FOO_CLICK: Mutex<usize> = Mutex::new(0);
> 
> fn foo(cx: Scope) -> Element {
>     let x = "Ahh";
>     render! {
>         div {
>             onclick: |_| {
>                 *FOO_CLICK.lock().unwrap() += 1;
>             },
>             format!("{x}")
>         }
>     }
> }
> 
> #[test]
> fn foo_test() {
>     let mut dom = VirtualDom::new(foo);
>     _ = dom.rebuild();
> 
>     // ElementId 2 = The dynamic text node
>     dom.handle_event("click", Rc::new(MouseData::default()), ElementId(2), true);
>     assert_eq!(*FOO_CLICK.lock().unwrap(), 1);
> }
> ```

Events cannot originate from a text node currently. You need to start the event on a dynamic element instead of a text node. I added some documentation to the `handle_event` function about the requirements on ElementId

**Pull request merged**
