### PR TITLE
Add fuzzing test to dioxus-core

### PR DESCRIPTION
**Pull request by Demonthos**
This PR adds a fuzzing test to dioxus-core that creates and then diffs random nodes and templates. It is notably missing code to fuzzes keyed diffing. Because this generates random nodes it will hit code paths that are more uncommon. The manual tests we already have can better test diffing nodes that are more similar.

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
It seems like fuzzing found a bug in core. Are you interested in digging into it, or would you like me to?

**Comment by Demonthos** [comment]
I can dig into it

**Comment by jkelleyrtp** [comment]
Do you mind resolving the conflicts? Seems like this now passes.

**Review by jkelleyrtp — APPROVED** [review]

**Comment by jkelleyrtp** [comment]
Yayyyyy

**Pull request merged**
