### PR TITLE
Added active class to router link

### PR DESCRIPTION
**Pull request by maccesch**
There should be a global way of setting the active class as well but I don't know how to properly do that. Please let me know what I can do.

### CODE REVIEW

**Comment by jkelleyrtp** [comment]
I'll be honest, I didn't know that "active" was a thing :-)

I think the implementation makes sense - but does that also mean that all "Link" components subscribe to the current route? I guess that makes sense?

Anyways - I think you might've made these changes on a previous commit (I rebased the local router PR before/after a merge) and the method to get current location/path has changed a bit.

Otherwise - looks good and is the approach I would suggest!

**Comment by maccesch** [comment]
Thanks for rebasing!
Yes, I’ve done work with Vue.js and Nuxt.js and there it works like this. 
I guess if we really want to provide ‘active’ there’s no way around subscribing to the route, right?

**Comment by maccesch** [comment]
Updated

**Review by jkelleyrtp — APPROVED** [review]
Looks great! I think we might (later) update the router service to provide some of the parsing/validation logic internally for some extra caching. But - routes change so infrequently that we don't gain that much performance anyways.

Thanks for adding this!

**Comment by maccesch** [comment]
@jkelleyrtp Hey, could you run the workflows again? Should work now

**Comment by jkelleyrtp** [comment]
Thank you!!

**Pull request merged**
