### PR TITLE
fix(serve): fixed long rebuilds with `dx serve`

### LINKED ISSUE #1862: `dx` perform long rebuilds until fast rebuilds take place; RA makes all rebuilds long (fullstack, Linux)
**Problem**

**Steps To Reproduce**

1. `git clone https://github.com/ealmloff/dioxus -b intigrate-collect-assets`
2. `cd dioxus`
3. install NASM (`nix profile install 'nixpkgs#nasm'`)
4. `cargo install --path ./packages/cli`
5. `dx create`
  <details><summary>answers</summary>

  ```
  [WARN] Favorite `gh:dioxuslabs/dioxus-template` not found in config, using it as a git repository: https://github.com/dioxuslabs/dioxus-template.git
  🤷   Project Name: fullstack
  [INFO] 🔧   Destination: /tmp/fullstack ...
  [INFO] 🔧   project-name: fullstack ...
  [INFO] 🔧   Generating template ...
  ✔ 🤷   What platform are you targeting? · Fullstack
  ✔ 🤷   Should the application use the dioxus router? · true
  ✔ 🤷   What backend framework are you using? · Axum
  ✔ 🤷   How do you want to create CSS? · Tailwind
  [INFO] 🔧   Moving generated files into: `/tmp/fullstack`...
  [INFO] 🔧   Initializing a fresh Git repository
  [INFO] ✨   Done! New project created /tmp/fullstack
  [INFO] Generated project at /tmp/fullstack
  ```

  </details>

6. `cd fullstack`
7. append this to `Cargo.toml`:
  ```toml
  [patch.crates-io]
  dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  dioxus = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  dioxus-router = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  # Dependent of dioxus-logger
  dioxus-core = { git = "https://github.com/ealmloff/dioxus", branch = "intigrate-collect-assets" }
  # dioxus-fullstack = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # dioxus = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # dioxus-router = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  # # Dependent of dioxus-logger
  # dioxus-core = { git = "https://github.com/ealmloff/dioxus", hash = "15dff7ad" }
  ```
8. add `index.html`:
  ```html
  <!doctype html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="/tailwind.css">
      <title>Title</title>
    </head>
    <body>
      <div id="main"></div>
    </body>
  </html>
  ```
9. replace content of `cx.render(rsx!{})` in `Home()` in `src/main.rs` with:
  ```rs
          div {
              class: "w-10 h-10 bg-red-500",
              "test"
          }
  ```
10. run `tailwindcss -w -i input.css -o public/tailwind.css` in PWD
11. run `dx serve --platform fullstack --hot-reload` in PWD
12. open `src/main.rs` in editor without auto-save and without rust-analyzer
13. Try changing Tailwind classes and see how long the rebuilds and hot reloading will be:
  ```
  w-10 h-10 -> w-44 h-44
  w-44 h-44 -> w-40 h-40
  bg-red-500 -> bg-green-500
  bg-green-500 -> bg-blue-500
  bg-blue-500 -> bg-yellow-500
  bg-yellow-500 -> bg-red-50
  bg-red-50 -> bg-red-100
  bg-red-100 -> bg-red-200
  bg-red-200 -> bg-red-300
  bg-red-300 -> bg-red-400
  ```
14. after rebuilds are sub 10 seconds try throwing rust-analyzer into the mix (open the main file in editor, which will run rust-analyzer LSP server; I'm using Neovim + lazy.nvim + `mrcjkb/rustaceanvim`)
15. wait for RA to be ready
16. continue changing Tailwind classes, the rebuild times should now be much longer
17. if RA is not used, then rebuilds again should be sub 10 seconds

I run tests with 2 `dx` versions (also changed `[patch.crates-io]` in `Cargo.toml`) and here is how many super long compilations I had to wait until sub 10 seconds compilations start to appear:
1. (15dff7ad) 1st build + 5 rebuilds
2. (latest) 1st build + 3 rebuilds
3. (latest) 1st build + 1 rebuild
4. (15dff7ad) 1st build + 1 rebuild
5. (15dff7ad) 1st build + 1 rebuild
6. (latest) 1st build + 1 rebuild

Here are some logs of all 6 tests (RA is not used unless said otherwise; also sometimes there is a compilation order note):

<details><summary>logs</summary>

<details><summary>test 1 logs</summary>

```
-1------------------------------------------------------------------------------
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
\ ⚙ Compiling reqwest 0.11.23 (registry+https://github.com/rust-lang/crates.io-index)
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              \ ⚙ Compiling reqwest 0.11.23 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
- ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...
Listening on 127.0.0.1:8080

Dioxus @ v0.4.1 [18:28:15]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 45460 millis

[INFO] A perfect compilation!

[INFO] 🚀 Starting development server...
================================================================================
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
================================================================================
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
/ ⚙ Compiling serde_repr 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)
\ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              / ⚙ Compiling serde_repr 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [18:32:34]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 92224 millis

[INFO] A perfect compilation!

================================================================================
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
Connected to hot reloading 🚀
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 83963 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 82377 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 38014 millis
================================================================================
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 86491 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
> Build Time Use : 2655 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
> Build Time Use : 2471 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
> Build Time Use : 2491 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
> Build Time Use : 3384 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
> Build Time Use : 3384 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 2 logs</summary>

```
-2------------------------------------------------------------------------------
$ dx serve --platform fullstack --hot-reload
[INFO] 🚅 Running build [Desktop] command...
- 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
| ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as\ ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...
- ⚙ Compiling dioxus-fullstack 0.4.3 (git+https://github.com/ealmloff/dioxus?branch=intigrate-collect-as
Dioxus @ v0.4.1 [19:06:03]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 129142 millis

[INFO] A perfect compilation!

Listening on 127.0.0.1:8080
thread 'main' panicked at /home/user/.cargo/git/checkouts/dioxus-5df58c476196bcfb/785b61a/packages/ful
lstack/src/serve_config.rs:117:37:
Failed to find index.html. Make sure the index_path is set correctly and the WASM application has been b
uilt.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
[INFO] 👑 Build done.
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
[INFO] 🚀 Starting development server...
================================================================================
$ dx serve --platform fullstack --hot-reload
[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
- ⚙ Compiling fnv 1.0.7 (registry+https://github.com/rust-lang/crates.io-index)
| 💼 Waiting to start build the project...                                                              - 💼 Waiting to start build the project...
[INFO] 🚩 Build completed: [./dist]
build desktop done
[INFO] 🚀 Starting development server...

Dioxus @ v0.4.1 [19:07:50]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 843 millis

[INFO] A perfect compilation!

Listening on 127.0.0.1:8080
- ⚙ Compiling libc 0.2.152 (registry+https://github.com/rust-lang/crates.io-index)
[INFO] 👑 Build done.
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
[INFO] 🚀 Starting development server...
[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
Connected to hot reloading 🚀
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
[INFO] 🚅 Running build [Desktop] command...
- 💼 Waiting to start build the project...                                                              [INFO] 🚅 Running build command...
- ⚙ Compiling rand_chacha 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              - ⚙ Compiling rand_chacha 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
/ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)                                              [INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [19:13:06]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 217057 millis

[INFO] A perfect compilation!

[INFO] 🚅 Running build [Desktop] command...
\ 💼 Waiting to start build the project...
[INFO] 🚅 Running build command...
/ ⚙ Compiling tokio 1.35.1 (registry+https://github.com/rust-lang/crates.io-index)
\ ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
/ ⚙ Compiling futures-lite 2.2.0 (registry+https://github.com/rust-lang/crates.io-index)
[WARN] in name section: index `0` is out of bounds for data
[WARN] in name section: index `1` is out of bounds for data
| ⚙ Compiling fullstack 0.1.0 (path+file:///tmp/fullstack)
[INFO] 👑 Build done.
[INFO] 🚩 Build completed: [./dist]
build desktop done
Listening on 127.0.0.1:8080

Project Reloaded: Changed 1 files. [19:16:48]


        > Profile : Debug
        > Hot Reload : RSX
        > Index Template : Custom [index.html]
        > URL Rewrite [index_on_404] : False

        > Build Time Use : 222029 millis

[INFO] A perfect compilation!

[INFO] dioxus_fullstack::render - Rebuilding vdom
[INFO] dioxus_fullstack::render - Suspense resolved
spinning up hot reloading
hot reloading ready
🔥 Hot Reload WebSocket connected
🔮 Finding updates since last compile...
finished
Connected to hot reloading 🚀
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 216854 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 5318 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4559 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 3 logs</summary>

```
-3------------------------------------------------------------------------------
> Build Time Use : 129582 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 216998 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 5392 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4609 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4378 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 4 logs</summary>

```
-4------------------------------------------------------------------------------
> Build Time Use : 123376 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 199674 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 4740 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4341 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4313 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 5 logs</summary>

```
-5------------------------------------------------------------------------------
> Build Time Use : 39845 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 80646 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 2503 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 2484 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 2446 millis
================================================================================
RA is on
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 58934 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
> Build Time Use : 56882 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
client + RA, server
> Build Time Use : 69118 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
client + RA, server
> Build Time Use : 70073 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
client + RA, server
> Build Time Use : 68866 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
client + RA, server
> Build Time Use : 69522 millis
--------------------------------------------------------------------------------
```

</details>

<details><summary>test 6 logs</summary>

```
-6------------------------------------------------------------------------------
> Build Time Use : 122749 millis
================================================================================
w-10 h-10 -> w-44 h-44
================================================================================
> Build Time Use : 206721 millis
================================================================================
w-44 h-44 -> w-40 h-40
================================================================================
> Build Time Use : 4878 millis
================================================================================
bg-red-500 -> bg-green-500
================================================================================
> Build Time Use : 4467 millis
================================================================================
bg-green-500 -> bg-blue-500
================================================================================
> Build Time Use : 4274 millis
================================================================================
RA is on
bg-blue-500 -> bg-yellow-500
================================================================================
> Build Time Use : 186793 millis
================================================================================
bg-yellow-500 -> bg-red-50
================================================================================
client, server, RA
> Build Time Use : 187481 millis
================================================================================
bg-red-50 -> bg-red-100
================================================================================
client, server, RA
> Build Time Use : 182991 millis
================================================================================
bg-red-100 -> bg-red-200
================================================================================
client + RA, server
> Build Time Use : 220144 millis
================================================================================
bg-red-200 -> bg-red-300
================================================================================
RA is off
> Build Time Use : 4818 millis
================================================================================
bg-red-300 -> bg-red-400
================================================================================
client + RA, server
> Build Time Use : 4064 millis
--------------------------------------------------------------------------------
```

</details>

</details>

In summary, rust-analyzer does affect the rebuild time in 100% cases, i.e., it makes rebuild as if they are "clean builds". The hot reloading time also increased from 1 or 2 seconds to 5 or 10 seconds (also, looks like the "clean rebuild" hot reloading time). Although last runs all took 1 build and 1 rebuild after which quick rebuild start to appear, but first runs include more rebuild, therefore, "long rebuild" counter is *random* (maybe some caching is present outside of the PWD that decreased the amount of "long rebuilds").

I don't know what to include into a container to make a portable environment and I don't know if it will be useful. Tested with editors without RA: Neovim, VSCodium — no difference in behavior.

**Environment:**
 - Dioxus version: `https://github.com/ealmloff/dioxus -b intigrate-collect-assets`
 - Rust version: nightly
 - OS info: Pop!_OS 22.04
 - App platform: fullstack

**Questionnaire**

- [x] I'm interested in fixing this myself but don't know where to start
- [ ] I would like to fix and I have a solution
- [ ] I don't have time to fix this right now, but maybe later

### PR DESCRIPTION
**Pull request by Andrew15-5**
The fix is 100% done, but the only remaining piece of puzzle is the:

```rs
static SERVER_RUST_FLAGS: &str = "";
// static SERVER_RUST_FLAGS: &str = "-C opt-level=2";
```

As I said here:
https://discord.com/channels/899851952891002890/1201227808060494025/1203791551797657640,
the O2 doesn't show any visual benefits, at least on Linux, so I think it
should be removed as this also will decrease the build times (by 1.45–2.1
times, I measured). Rebuilds also tend to be a _bit_ faster and startup time
after SIGINT also tend to be in the "0.5 s" range more often.

Fixes #1862.

### CODE REVIEW

**Comment by Andrew15-5** [comment]
```rs
// The `opt-level=2` increases build times, but can noticeably decrease time
// between saving changes and being able to interact with an app. The "overall"
// time difference (between having and not having the optimization) can be
// almost imperceptible (~1 s) but also can be very noticeable (~6 s) — depends
// on setup (hardware, OS, browser, idle load).
static SERVER_RUST_FLAGS: &str = "-C opt-level=2";
```

**Review by mrxiaozhuox — APPROVED** [review]
LGTM

**Review by ealmloff — APPROVED** [review]
Thank you!

**Comment by Andrew15-5** [comment]
It was hard and fun to debug, but now I at least have some idea of how CLI works, so hopefully I'll do more CLI improvements down the road. (lack of time is the main problem, as always)

**Pull request merged**
